deploy:
  type: git
  repository: https://github.com/vegawhua/vegawhua.github.io.git
  branch: master

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: maupassant
